import { expect, test } from '@playwright/test'
import { imageFile } from './fixtures'

test('setup is labeled and generation requires a picture', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Little sums, big pictures.' })).toBeVisible()
  await expect(page.getByLabel('Auto size from picture')).toBeChecked()
  await expect(page.getByLabel('Columns', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Rows', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Columns', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Rows', { exact: true })).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Create puzzle' })).toBeDisabled()
  await page.getByLabel('Auto size from picture').uncheck()
  await expect(page.getByLabel('Columns', { exact: true })).toHaveValue('16')
  await expect(page.getByLabel('Rows', { exact: true })).toHaveValue('20')
  await expect(page.getByRole('button', { name: 'Create puzzle' })).toBeDisabled()
  await page.getByLabel('Rows', { exact: true }).fill('65')
  await expect(page.getByText('Enter a whole number from 4 to 64.')).toBeVisible()
})

test('fresh defaults generate an auto-sized multi-map puzzle and both can be turned off', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('1. Choose a picture').setInputFiles(await imageFile(page))
  await expect(page.getByLabel('Columns', { exact: true })).toHaveValue('25')
  await expect(page.getByLabel('Rows', { exact: true })).toHaveValue('13')
  await page.getByRole('button', { name: 'Create puzzle' }).click()
  await expect(page.getByRole('table', { name: '13 by 25 addition puzzle' }).locator('td')).toHaveCount(325)
  const defaultResults = await page.locator('.app-shell .color-key td').evaluateAll(cells => cells.map(cell => cell.getAttribute('data-results')!.split(',')))
  expect(defaultResults.length).toBeGreaterThan(1)
  expect(defaultResults.length).toBeLessThanOrEqual(8)
  expect(defaultResults.every(results => results.length >= 1 && results.length <= 3)).toBe(true)
  expect(defaultResults.some(results => results.length === 3)).toBe(true)
  await page.getByText('Advanced', { exact: true }).click()
  await expect(page.getByLabel('Multiple results per color')).toBeChecked()
  await page.getByLabel('Multiple results per color').uncheck()
  await page.getByLabel('Auto size from picture').uncheck()
  await expect(page.getByRole('button', { name: 'Print puzzle', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Create puzzle' }).click()
  await expect(page.getByRole('table', { name: '20 by 16 addition puzzle' }).locator('td')).toHaveCount(320)
  const singleResults = await page.locator('.app-shell .color-key td').evaluateAll(cells => cells.map(cell => cell.getAttribute('data-results')!.split(',')))
  expect(singleResults.length).toBeGreaterThan(0)
  expect(singleResults.every(results => results.length === 1)).toBe(true)
})
